### PR TITLE
Dockerize the app

### PR DESCRIPTION
**Pull request by TheOtherUnknown**
This commit adds a Dockerfile and instructions on how to use it.

My data will be added to the JSON file in another PR.

### CODE REVIEW

**Review by thebouv — COMMENTED** [review]
I have constructive feedback to give on the Dockerfile, but saving those to ask:

Did you run this? Because plotly's `fig.show()` launches the default renderer (open in default browser in a tab) when ran locally, when run inside docker with your example run command, the container runs and exits without showing. Because in the context of the container, there is no reaching out to the browser to show the visualization.

Were you able to run it and have it work?

**Comment by TheOtherUnknown** [comment]
So, I wasn't aware of the browser part when I wrote the Dockerfile. I thought it just output some data to the command line, and was done. I tested, saw the output, and thought I did it correctly. 

Docker containers cannot really open a browser tab. I'll have to serve the graph via a webserver using an alternative plotly rendering engine.
What alternative rendering engine would you prefer I use (for the Docker container only)? Or, would you rather close the PR and forget about Docker?

**Comment by thebouv** [comment]
No, I think it is worth it. I didn't get any more time to research it, but `fig.show()` on my machine will throw open a browser tab with random assigned port. It doesn't stay hosted there -- it throws up the HTML then dies. Because if you referesh it fails.

However, I think dockerizing it is a good idea. I mean, why not? Just will have to look into what else `show()` can do.  If it can dump the HTML/CSS/JS out instead of temporarily creating it for the single browser view it can easily be thrown at python's built in simple server. Then the only change really needed to the Dockerfile is to run the simple server, and only python change is to allow for dumping the HTML instead of just default `show()`.

On the plus side, your PR still counts for your Hacktoberfest contribution whether it stays open, gets merged, or whatever.

I think its worth iterating on this if just for the fun of it. If you didn't dockerize it I was going to take a stab myself.

**Comment by TheOtherUnknown** [comment]
Alright, I'll take a took at exporting it as HTML. Some basic Googling says this won't be too hard. This, however, will require some sort of additional if statement in the code. 

The app works and opens a browser tab if it run it outside of a container.

**Comment by thebouv** [comment]
Plotly is weird it seems.

If you use `fig.show()` the default will open a browser and serve a single request that sends the HTML output.

But there's no inherent easy way to just save that HTML as-is.

I've been playing with it and have changed it to `fig.show(renderer='iframe')` which at least generates the HTML and writes it to a folder called `iframe_figures`.

Playing with it still. :)

**Comment by TheOtherUnknown** [comment]
Commit b045734 uses a webserver to serve the graph on port 8000 via python. See how that works out for you.

**Comment by thebouv** [comment]
Nice changes! I just did the same. Not sure why it took me so long to find the `write_html` method. Got lost in the docs about renderers I guess.

I made some updates to your Dockerfile for best practice reasons (overkill for this project, this is more to inform @zbouvier) with lots of comments too.

You can see mine here:  https://github.com/thebouv/IUS-Hacktoberfest/blob/master/Dockerfile

I think yours is fine and @zbouvier should merge it.  Mine is overkill on good practices, so use some of it if you want. I may still submit a PR for another point towards Hacktoberfest, or I may just let it stay over on my repo.

This was fun. :)

**Review by thebouv — APPROVED** [review]

**Review by lilbouv — APPROVED** [review]
👍

**Pull request merged**
